fix(config): replace legacy configuration properties
arkaitzgarro/elastic-apm-laravel pull request #154
Opened 2021-12-14 08:32 UTC by arkaitzgarro

Closes https://github.com/arkaitzgarro/elastic-apm-laravel/issues/153

2021-12-20 08:50 UTC, countless-integers requested changes
I'm a bit confused, because [config](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/baaa1d347d4588ea5ddc4834ff50637a4ab29ccf/config/elastic-apm-laravel.php) has not changed and neither did the env variables which are mentioned in the [README](https://github.com/arkaitzgarro/elastic-apm-laravel#agent-configuration).

2021-12-21 16:30 UTC, arkaitzgarro commented
> I'm a bit confused, because [config](https://github.com/arkaitzgarro/elastic-apm-laravel/blob/baaa1d347d4588ea5ddc4834ff50637a4ab29ccf/config/elastic-apm-laravel.php) has not changed and neither did the env variables which are mentioned in the [README](https://github.com/arkaitzgarro/elastic-apm-laravel#agent-configuration).

Yes, the only purpose of this PR is to remove the deprecation notifications comming from `nipwaayoni` package, because we are using legacy propeties. If we change sthe config file, we'll need to release a major version right?

2022-01-06 10:20 UTC, leovalen commented
The deprecations are generating a lot of noise in the log, so it's be nice to have this one merged.

2022-01-06 14:22 UTC, countless-integers approved these changes

2022-01-07 07:50 UTC, merged